CREATE TABLE IF NOT EXISTS users (
  user_id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100),
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  account_bal DECIMAL
);

CREATE TABLE IF NOT EXISTS groups (
  group_id SERIAL PRIMARY KEY NOT NULL,
  group_name VARCHAR(100),
);